services:
  core-db:
    image: mysql:8.0
    container_name: core-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${AUTH_DB_NAME:-auth_db}
      MYSQL_USER: ${AUTH_DB_USERNAME:-auth_user}
      MYSQL_PASSWORD: ${AUTH_DB_PASSWORD:-auth_password}
      MYSQL_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD:-root_password}
    ports:
      - "${AUTH_DB_PORT:-3307}:3306"
    volumes:
      - core-db-data:/var/lib/mysql
      - ./mysql-init/core-db:/docker-entrypoint-initdb.d:ro

volumes:
  core-db-data:
