import { beforeEach, describe, expect, it, vi } from 'vitest'
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import SettlementReport from './SettlementReport'
import { listSettlements, settlementSummary, settlementDetail, settlementCommand } from '../api/settlementApi'
vi.mock('../api/settlementApi', () => ({ listSettlements: vi.fn(), settlementSummary: vi.fn(), settlementDetail: vi.fn(), settlementCommand: vi.fn() }))
const row = { id: 1, festivalId: 42, festivalName: '검증 행사', status: 'CALCULATED', grossPaymentAmount: 100000,
  grossRefundedFaceAmount: 0, customerRefundAmount: 0, cancellationPenaltyAmount: 0, platformFeeAmount: 7500, adjustmentAmount: 0, payoutAmount: 92500, lines: [], auditLogs: [] }
beforeEach(() => {
  vi.resetAllMocks()
  listSettlements.mockResolvedValue({ data: { data: [], meta: { pagination: { totalPages: 0, hasNext: false, hasPrev: false } } } })
  settlementSummary.mockResolvedValue({ data: { data: row } })
  settlementDetail.mockResolvedValue({ data: { data: row } })
})
describe('SettlementReport', () => {
  it('searches names without test-channel, method or ID controls', async () => {
    render(<SettlementReport />)
    await screen.findByText('조회 조건에 해당하는 정산이 없습니다.')
    expect(screen.queryByRole('checkbox')).toBeNull()
    expect(screen.queryByLabelText('결제수단')).toBeNull()
    expect(screen.queryByLabelText('페스티벌 ID')).toBeNull()
    fireEvent.change(screen.getByLabelText('페스티벌 이름'), { target: { value: '음악' } })
    fireEvent.change(screen.getByLabelText('주최자 이름'), { target: { value: '홍길동' } })
    fireEvent.click(screen.getByRole('button', { name: '검색' }))
    await waitFor(() => expect(listSettlements.mock.lastCall[1]).toEqual({ festivalName: '음악', hostName: '홍길동', page: 0, size: 20 }))
  })
  it('includes the selected end date and requests the next page', async () => {
    listSettlements.mockResolvedValue({ data: { data: [row], meta: { pagination: { totalPages: 2, hasNext: true } } } })
    render(<SettlementReport />)
    await screen.findByRole('button', { name: '검증 행사 상세' })
    fireEvent.change(screen.getByLabelText('시작일'), { target: { value: '2026-09-01' } })
    fireEvent.change(screen.getByLabelText('종료일'), { target: { value: '2026-09-02' } })
    fireEvent.click(screen.getByRole('button', { name: '검색' }))
    await waitFor(() => expect(listSettlements.mock.lastCall[1]).toMatchObject({ from: '2026-08-31T15:00:00.000Z', to: '2026-09-02T15:00:00.000Z', page: 0 }))
    await waitFor(() => expect(screen.getByRole('button', { name: '다음' }).disabled).toBe(false))
    fireEvent.click(screen.getByRole('button', { name: '다음' }))
    await waitFor(() => expect(listSettlements.mock.lastCall[1].page).toBe(1))
  })
  it('keeps audit history collapsed and closes detail accessibly', async () => {
    listSettlements.mockResolvedValue({ data: { data: [row], meta: { pagination: { totalPages: 1 } } } })
    render(<SettlementReport />)
    fireEvent.click(await screen.findByRole('button', { name: '검증 행사 상세' }))
    const history = await screen.findByText('처리 기록')
    expect(history.closest('details').open).toBe(false)
    expect(screen.getByRole('dialog').textContent).toContain('주최자에게 지급할 금액')
    fireEvent.click(screen.getByRole('button', { name: '상세 닫기' }))
    expect(screen.queryByRole('dialog')).toBeNull()
  })
  it('shows loading before receiving a response', () => {
    listSettlements.mockReturnValue(new Promise(() => {}))
    render(<SettlementReport />)
    expect(screen.getByRole('status').textContent).toContain('불러오는 중')
  })
  it('shows empty state and disables pagination', async () => {
    render(<SettlementReport />)
    expect(await screen.findByText('조회 조건에 해당하는 정산이 없습니다.')).toBeTruthy()
    expect(screen.getByRole('button', { name: '다음' }).disabled).toBe(true)
  })
  it('shows a retryable error', async () => {
    listSettlements.mockRejectedValue(new Error('offline'))
    render(<SettlementReport />)
    expect((await screen.findByRole('alert')).textContent).toContain('불러오지 못했습니다')
    expect(screen.getByRole('button', { name: '새로고침' })).toBeTruthy()
  })
  it('never exposes admin commands or audit data to HOST', async () => {
    listSettlements.mockResolvedValue({ data: { data: [row], meta: { pagination: { totalPages: 1 } } } })
    render(<SettlementReport host />)
    fireEvent.click(await screen.findByRole('button', { name: '검증 행사 상세' }))
    await screen.findByText('수수료와 환불 계산 근거')
    expect(screen.queryByRole('button', { name: '금액 확정' })).toBeNull()
    expect(screen.queryByText('처리 기록')).toBeNull()
    expect(screen.queryByLabelText('주최자 이름')).toBeNull()
    expect(settlementDetail).toHaveBeenCalledWith(true, 1)
  })
  it('requires confirmation and prevents duplicate command clicks', async () => {
    listSettlements.mockResolvedValue({ data: { data: [row], meta: { pagination: { totalPages: 1 } } } })
    settlementCommand.mockReturnValue(new Promise(() => {}))
    render(<SettlementReport />)
    fireEvent.click(await screen.findByRole('button', { name: '검증 행사 상세' }))
    fireEvent.click(await screen.findByRole('button', { name: '금액 확정' }))
    expect(settlementCommand).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('button', { name: '확인하고 실행' }))
    fireEvent.click(screen.getByRole('button', { name: '처리 중…' }))
    expect(settlementCommand).toHaveBeenCalledTimes(1)
  })
  it('offers reapproval only before payout', async () => {
    listSettlements.mockResolvedValue({ data: { data: [row], meta: { pagination: { totalPages: 1 } } } })
    settlementDetail.mockResolvedValue({ data: { data: { ...row, status: 'ADJUSTMENT_REQUIRED', paidAt: null, proposedPayoutAmount: 46250 } } })
    render(<SettlementReport />)
    fireEvent.click(await screen.findByRole('button', { name: '검증 행사 상세' }))
    expect(await screen.findByRole('button', { name: '변경 금액 승인' })).toBeTruthy()
    expect(screen.queryByRole('button', { name: '지급 완료 기록' })).toBeNull()
  })
})
