### 로그인 - 성공 (200)
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "username": "test@naver.com",
  "password": "test1234"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
%}


### 내 정보 조회
GET http://localhost:8080/api/users/me
Authorization: Bearer {{accessToken}}

### 닉네임 수정 - 성공
PATCH http://localhost:8080/api/users/me/nickname
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "nickname": "홍이"
}

### 비밀번호 변경 - 성공
PATCH http://localhost:8080/api/users/me/password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "currentPassword": "test1234",
  "newPassword": "newpassword1234",
  "newPasswordConfirm": "newpassword1234"
}