server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${AUTH_DB_HOST:localhost}:${AUTH_DB_PORT:3307}/${AUTH_DB_NAME:auth_db}
    username: ${AUTH_DB_USERNAME:auth_user}
    password: ${AUTH_DB_PASSWORD:auth_password}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

jwt:
  secret: ${JWT_SECRET:CHANGE_ME_IN_ENV}
