server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: festival-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/festivals/**,/api/ticket-types/**
        - id: organizer-applications
          uri: http://localhost:8082
          predicates:
            - Path=/api/organizer-applications/**
        - id: admin-organizer-applications
          uri: http://localhost:8082
          predicates:
            - Path=/api/admin/organizer-applications/**
        - id: organizer-festivals
          uri: http://localhost:8082
          predicates:
            - Path=/api/organizer/festivals/**
        - id: reservation-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/reservations/**

jwt:
  secret: ${JWT_SECRET:CHANGE_ME_IN_ENV}
